/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Gui
 */
public class pokeScreen extends javax.swing.JFrame {

    /**
     * Creates new form pokeScreen
     */
    public pokeScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        selectBox1 = new javax.swing.JComboBox<>();
        selectBox2 = new javax.swing.JComboBox<>();
        lutarButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 635));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("SELECIONE OS POKEFIGHTERS");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(270, 60, 350, 40);

        selectBox1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Charmander", "Squirtle", "Bulbasaur" }));
        selectBox1.setBorder(null);
        selectBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(selectBox1);
        selectBox1.setBounds(150, 180, 120, 20);

        selectBox2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        selectBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Charmander", "Squirtle", "Bulbasaur" }));
        selectBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(selectBox2);
        selectBox2.setBounds(620, 180, 120, 22);

        lutarButton.setBackground(new java.awt.Color(255, 0, 0));
        lutarButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lutarButton.setText("Lutar");
        lutarButton.setBorder(null);
        lutarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lutarButtonActionPerformed(evt);
            }
        });
        getContentPane().add(lutarButton);
        lutarButton.setBounds(390, 180, 90, 21);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pokeball background.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 635);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lutarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lutarButtonActionPerformed
        String pokemon1Selected = pokemon1();
        String pokemon2Selected = pokemon2();
        Pokemon pokemon1 = null;
        Pokemon pokemon2 = null;
        
        switch(pokemon1Selected) {
            case "Charmander":
                pokemon1 = new Pokemon("Charmander", 500, 100, "fogo", "planta");
            break;
                
            case "Squirtle":
                pokemon1 = new Pokemon("Squirtle", 700, 50, "agua", "fogo");
            break;
            
            case "Bulbasaur":
                pokemon1 = new Pokemon("Bulbasaur", 600, 75, "planta", "agua");
            break;
        }
        
        switch(pokemon2Selected) {
            case "Charmander":
                pokemon2 = new Pokemon("Charmander", 500, 100, "fogo", "planta");
            break;

            case "Squirtle":
                pokemon2 = new Pokemon("Squirtle", 700, 50, "agua", "fogo");
            break;
            
            case "Bulbasaur":
                pokemon2 = new Pokemon("Bulbasaur", 600, 75, "planta", "agua");
            break;
        }
        
        Batalhar batalha = new Batalhar(pokemon1, pokemon2);
        this.setVisible(false);

        
        if(pokemon1.vida > 0) {
            System.out.println(pokemon1.nome + " é o grande vencedor");
            
            switch(pokemon1.nome) {
                case "Charmander":
                    charmanderWin gifChar = new charmanderWin();
                    gifChar.setVisible(true);
                break;
                
                case "Squirtle":
                    squirtleWin gifSqui = new squirtleWin();
                    gifSqui.setVisible(true);
                break;
                
                case "Bulbasaur":
                    bulbasaurWin gifBulba = new bulbasaurWin();
                    gifBulba.setVisible(true);
                break;
            }
        } else {
            System.out.println(pokemon2.nome + " é o grande vencedor");
            
            switch(pokemon2.nome) {
                case "Charmander":
                    charmanderWin gif = new charmanderWin();
                    gif.setVisible(true);
                break;
                
                case "Squirtle":
                    squirtleWin gifSqui = new squirtleWin();
                    gifSqui.setVisible(true);
                break;
                
                case "Bulbasaur":
                    bulbasaurWin gifBulba = new bulbasaurWin();
                    gifBulba.setVisible(true);
                break;
            }
        }
    }//GEN-LAST:event_lutarButtonActionPerformed

    private void selectBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBox1ActionPerformed
            
    }//GEN-LAST:event_selectBox1ActionPerformed

    private void selectBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectBox2ActionPerformed
        
    }//GEN-LAST:event_selectBox2ActionPerformed

    public String pokemon1() {
        return selectBox1.getSelectedItem().toString(); 
    }
    
    public String pokemon2() {
        return selectBox2.getSelectedItem().toString(); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pokeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pokeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pokeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pokeScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pokeScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JButton lutarButton;
    public javax.swing.JComboBox<String> selectBox1;
    public javax.swing.JComboBox<String> selectBox2;
    // End of variables declaration//GEN-END:variables
}
